version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - canny-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - canny-network    environment:
      - APP_ENV=docker
    volumes:
      - ./backend/config.docker.json:/app/config.docker.json

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    networks:
      - canny-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=canny_clone
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

networks:
  canny-network:
    driver: bridge

volumes:
  postgres-data:
